# Generated by Django 4.2.15 on 2024-09-14 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlianzaColaborativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Alianzas Colaborativas',
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Capacitación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Capacitación')),
            ],
            options={
                'verbose_name_plural': 'Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name_plural': 'Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Comuna')),
            ],
            options={
                'verbose_name_plural': 'Comunas',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('actividad_comercial', models.CharField(max_length=255)),
                ('tamaño_empresa', models.CharField(choices=[('MCR', 'Micro'), ('PE', 'Pequeña'), ('ME', 'Mediana'), ('GR', 'Grande')], max_length=3)),
                ('tipo_empresa', models.CharField(choices=[('SPA', 'Sociedad por Acciones (SpA)'), ('SRL', 'Sociedad de Responsabilidad Limitada (SRL)'), ('SA', 'Sociedad Anónima (SA)'), ('EIRL', 'Empresa Individual de Responsabilidad Limitada (EIRL)'), ('COOP', 'Cooperativa'), ('FI', 'Fundación o Institución')], max_length=4)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=100)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.ciudad')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.comunas')),
            ],
            options={
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Experiencia Laboral',
            },
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name_plural': 'Motivos',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name_plural': 'Nacionalidad',
            },
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('id_interno', models.CharField(blank=True, max_length=50, null=True)),
                ('mes', models.CharField(max_length=2)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('seguimiento', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('estado_seguimiento', models.CharField(choices=[('Anulada', 'Anulada'), ('Cerrada con colocados', 'Cerrada con colocados'), ('En espera FeedBack', 'En espera FeedBack'), ('En proceso de selección', 'En proceso de selección'), ('Pausada', 'Pausada'), ('Vigente', 'Vigente')], max_length=50)),
                ('estado_oferta', models.CharField(choices=[('Cerrada', 'Cerrada'), ('Activa', 'Activa')], max_length=10)),
                ('observaciones_seguimiento', models.TextField(blank=True, null=True)),
                ('fecha_prevista_incorporacion', models.DateField()),
                ('fecha_incorporacion_trabajo', models.DateField()),
                ('ocupacion_ofrecida', models.CharField(max_length=255)),
                ('rut_empresa', models.CharField(max_length=12, unique=True)),
                ('telefono_empresa', models.CharField(max_length=15)),
                ('giro_empresa', models.CharField(max_length=255)),
                ('nombre_solicitante', models.CharField(max_length=255)),
                ('run_solicitante', models.CharField(max_length=12)),
                ('fecha_nacimiento_solicitante', models.DateField()),
                ('cargo_solicitante', models.CharField(max_length=255)),
                ('direccion_empresa', models.CharField(max_length=255)),
                ('email_empresa', models.EmailField(max_length=254)),
                ('experiencia_requerida', models.PositiveIntegerField()),
                ('escolaridad_requerida', models.CharField(choices=[('basica_incompleta', 'Básica Incompleta'), ('basica_completa', 'Básica Completa'), ('media_incompleta', 'Media Incompleta'), ('media_completa', 'Media Completa'), ('tecnica_incompleta', 'Técnica Incompleta'), ('tecnica_completa', 'Técnica Completa'), ('universitaria_incompleta', 'Universitaria Incompleta'), ('universitaria_completa', 'Universitaria Completa'), ('postgrado', 'Postgrado'), ('ninguna', 'Ninguna')], max_length=30, verbose_name='Escolaridad')),
                ('rango_salarios', models.CharField(max_length=50)),
                ('sexo_requerido', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('relacion_contractual', models.CharField(max_length=255)),
                ('actividades_trabajador', models.TextField()),
                ('jornada_trabajo', models.CharField(max_length=255)),
                ('licencia_conducir_requerida', models.CharField(blank=True, max_length=50, null=True)),
                ('lugar_trabajo_obra', models.CharField(max_length=255)),
                ('alianza_colaborativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registro.alianzacolaborativa')),
                ('ciudad_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_empresa', to='Registro.ciudad')),
                ('ciudad_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_trabajo', to='Registro.ciudad')),
                ('comuna_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_trabajo', to='Registro.comunas')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.empresa')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registro.nacionalidad', verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name_plural': 'Ofertas de Empleo',
            },
        ),
        migrations.CreateModel(
            name='Oficio_Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Oficio Profesión',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_atencion', models.DateField(verbose_name='Fecha de Atención')),
                ('tipo_documento', models.CharField(choices=[('RUN', 'RUN'), ('Pasaporte', 'Pasaporte'), ('Otro', 'Otro')], default='RUN', max_length=20, verbose_name='Tipo de Documento')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('pasaporte', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasaporte o DNI')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('telefono2', models.CharField(max_length=15, verbose_name='Teléfono Secundario')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('persona_con_discapacidad', models.CharField(choices=[('si', 'Sí'), ('no', 'No')], max_length=2, verbose_name='Persona con Discapacidad')),
                ('situacion_migrante', models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular'), ('no_aplica', 'No Aplica')], max_length=10, verbose_name='Situación Migrante')),
                ('escolaridad', models.CharField(choices=[('basica_incompleta', 'Básica Incompleta'), ('basica_completa', 'Básica Completa'), ('media_incompleta', 'Media Incompleta'), ('media_completa', 'Media Completa'), ('tecnica_incompleta', 'Técnica Incompleta'), ('tecnica_completa', 'Técnica Completa'), ('universitaria_incompleta', 'Universitaria Incompleta'), ('universitaria_completa', 'Universitaria Completa'), ('postgrado', 'Postgrado'), ('ninguna', 'Ninguna')], max_length=30, verbose_name='Escolaridad')),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registro.ciudad', verbose_name='Ciudad')),
                ('comuna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registro.comunas', verbose_name='Comuna')),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Programas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Programa')),
            ],
            options={
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Sector de Residencia')),
            ],
            options={
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Discapacidad')),
            ],
            options={
                'verbose_name_plural': 'Tipo Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True)),
                ('registro_bne', models.CharField(choices=[('registrado', 'Registrado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('capacitaciones', models.ManyToManyField(blank=True, to='Registro.capacitacion', verbose_name='Capacitaciones')),
                ('motivo', models.ManyToManyField(to='Registro.motivo', verbose_name='Motivos')),
                ('oferta_empleo', models.ManyToManyField(to='Registro.ofertaempleo', verbose_name='Oferta de Empleo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='Registro.persona')),
            ],
            options={
                'verbose_name_plural': 'Visitas OMIL',
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='derivados_programas',
            field=models.ManyToManyField(blank=True, to='Registro.programas', verbose_name='Derivados de Programas'),
        ),
        migrations.AddField(
            model_name='persona',
            name='nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registro.nacionalidad', verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='persona',
            name='profesion_oficio',
            field=models.ManyToManyField(related_name='personas', to='Registro.oficio_profesion', verbose_name='Profesión u Oficio'),
        ),
        migrations.AddField(
            model_name='persona',
            name='sector_residencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registro.sectores', verbose_name='Sector de Residencia'),
        ),
        migrations.AddField(
            model_name='persona',
            name='tipo_discapacidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registro.tipodiscapacidad', verbose_name='Tipo de Discapacidad'),
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_derivacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], max_length=50)),
                ('oferta_empleo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='Registro.ofertaempleo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='Registro.persona')),
            ],
            options={
                'verbose_name_plural': 'Derivaciones a ofertas',
            },
        ),
    ]
