# Generated by Django 4.2.15 on 2024-09-14 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_remove_ofertaempleo_ciudad_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ofertaempleo',
            old_name='titulo',
            new_name='id_bne',
        ),
    ]
