# Generated by Django 4.2.15 on 2024-09-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_rename_titulo_ofertaempleo_id_bne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='tamaño_empresa',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='tipo_empresa',
        ),
        migrations.AddField(
            model_name='empresa',
            name='cantidad_trabajadores',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='tamagno_empresa',
            field=models.CharField(blank=True, choices=[('MCR', 'Micro'), ('PE', 'Pequeña'), ('ME', 'Mediana'), ('GR', 'Grande')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='id_bne',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='licencia_conducir_requerida',
            field=models.CharField(blank=True, choices=[('A1', 'Clase A1'), ('A2', 'Clase A2'), ('A3', 'Clase A3'), ('A4', 'Clase A4'), ('A5', 'Clase A5'), ('B', 'Clase B'), ('C', 'Clase C'), ('D', 'Clase D'), ('E', 'Clase E'), ('F', 'Clase F'), ('No Requiere', 'No Requiere')], max_length=20, null=True),
        ),
    ]
